version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    image: halimkun/ists:latest
    ports:
      - "9000:3000"
    environment:
      NODE_ENV: production
    env_file:
      - .env.production
