version: '3.8'

services:
  app:
    image: filetrack:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:3000"
    environment:
      NODE_ENV: production
    command: ["node", ".output/server/index.mjs"]
